-- All chains listed on DEX Screener that Lockabox knows by id (owner request 2026-09-27). They get DEX Screener discovery, snapshots,
-- the liquidity gate and "View on DEX Screener"; in-app swap stays off (no rpc_url, DECISIONS #10) and DexPaprika new-pool
-- discovery stays on the original six chains only (free credit budget). Ids first seen in recorded feeds: avalanche, near, ton,
-- pulsechain, tron; the rest follow DEX Screener's URLs and should be checked against live feeds. The worker also registers any
-- chain id it meets in a DEX Screener feed that is not listed here (worker/ingest.ts `registerChains`).
alter table chains drop constraint chains_family_check;
alter table chains add constraint chains_family_check check (family in ('solana', 'evm', 'other'));

insert into chains (id, name, family, enabled, swap_enabled, evm_chain_id, explorer_tx_url, explorer_token_url, sort) values
  ('arbitrum', 'Arbitrum', 'evm', true, false, 42161, 'https://arbiscan.io/tx/{tx}', 'https://arbiscan.io/token/{address}', 14),
  ('polygon', 'Polygon', 'evm', true, false, 137, 'https://polygonscan.com/tx/{tx}', 'https://polygonscan.com/token/{address}', 15),
  ('avalanche', 'Avalanche', 'evm', true, false, 43114, 'https://snowtrace.io/tx/{tx}', 'https://snowtrace.io/token/{address}', 16),
  ('optimism', 'Optimism', 'evm', true, false, 10, 'https://optimistic.etherscan.io/tx/{tx}', 'https://optimistic.etherscan.io/token/{address}', 17),
  ('blast', 'Blast', 'evm', true, false, 81457, 'https://blastscan.io/tx/{tx}', 'https://blastscan.io/token/{address}', 18),
  ('monad', 'Monad', 'evm', true, false, 143, 'https://monadscan.com/tx/{tx}', 'https://monadscan.com/token/{address}', 19),
  ('hyperevm', 'HyperEVM', 'evm', true, false, 999, 'https://hyperevmscan.io/tx/{tx}', 'https://hyperevmscan.io/token/{address}', 20),
  ('sui', 'Sui', 'other', true, false, null, 'https://suivision.xyz/txblock/{tx}', 'https://suivision.xyz/coin/{address}', 21),
  ('ton', 'TON', 'other', true, false, null, 'https://tonviewer.com/transaction/{tx}', 'https://tonviewer.com/{address}', 22),
  ('tron', 'Tron', 'other', true, false, null, 'https://tronscan.org/#/transaction/{tx}', 'https://tronscan.org/#/token20/{address}', 23),
  ('pulsechain', 'PulseChain', 'evm', true, false, 369, 'https://scan.pulsechain.com/tx/{tx}', 'https://scan.pulsechain.com/token/{address}', 24),
  ('sonic', 'Sonic', 'evm', true, false, 146, 'https://sonicscan.org/tx/{tx}', 'https://sonicscan.org/token/{address}', 25),
  ('berachain', 'Berachain', 'evm', true, false, 80094, 'https://berascan.com/tx/{tx}', 'https://berascan.com/token/{address}', 26),
  ('abstract', 'Abstract', 'evm', true, false, 2741, 'https://abscan.org/tx/{tx}', 'https://abscan.org/token/{address}', 27),
  ('unichain', 'Unichain', 'evm', true, false, 130, 'https://uniscan.xyz/tx/{tx}', 'https://uniscan.xyz/token/{address}', 28),
  ('linea', 'Linea', 'evm', true, false, 59144, 'https://lineascan.build/tx/{tx}', 'https://lineascan.build/token/{address}', 29),
  ('mantle', 'Mantle', 'evm', true, false, 5000, 'https://mantlescan.xyz/tx/{tx}', 'https://mantlescan.xyz/token/{address}', 30),
  ('scroll', 'Scroll', 'evm', true, false, 534352, 'https://scrollscan.com/tx/{tx}', 'https://scrollscan.com/token/{address}', 31),
  ('zksync', 'zkSync', 'evm', true, false, 324, 'https://explorer.zksync.io/tx/{tx}', 'https://explorer.zksync.io/token/{address}', 32),
  ('apechain', 'ApeChain', 'evm', true, false, 33139, 'https://apescan.io/tx/{tx}', 'https://apescan.io/token/{address}', 33),
  ('seiv2', 'Sei', 'evm', true, false, 1329, 'https://seitrace.com/tx/{tx}', 'https://seitrace.com/token/{address}', 34),
  ('xlayer', 'X Layer', 'evm', true, false, 196, 'https://www.oklink.com/xlayer/tx/{tx}', 'https://www.oklink.com/xlayer/token/{address}', 35),
  ('cronos', 'Cronos', 'evm', true, false, 25, 'https://cronoscan.com/tx/{tx}', 'https://cronoscan.com/token/{address}', 36),
  ('celo', 'Celo', 'evm', true, false, 42220, 'https://celoscan.io/tx/{tx}', 'https://celoscan.io/token/{address}', 37),
  ('fantom', 'Fantom', 'evm', true, false, 250, 'https://ftmscan.com/tx/{tx}', 'https://ftmscan.com/token/{address}', 38),
  ('near', 'NEAR', 'other', true, false, null, 'https://nearblocks.io/txns/{tx}', 'https://nearblocks.io/token/{address}', 39),
  ('aptos', 'Aptos', 'other', true, false, null, 'https://explorer.aptoslabs.com/txn/{tx}', 'https://explorer.aptoslabs.com/coin/{address}', 40),
  ('story', 'Story', 'evm', true, false, 1514, 'https://www.storyscan.io/tx/{tx}', 'https://www.storyscan.io/token/{address}', 41),
  ('core', 'Core', 'evm', true, false, 1116, 'https://scan.coredao.org/tx/{tx}', 'https://scan.coredao.org/token/{address}', 42),
  ('metis', 'Metis', 'evm', true, false, 1088, 'https://andromeda-explorer.metis.io/tx/{tx}', 'https://andromeda-explorer.metis.io/token/{address}', 43),
  ('moonbeam', 'Moonbeam', 'evm', true, false, 1284, 'https://moonscan.io/tx/{tx}', 'https://moonscan.io/token/{address}', 44),
  ('zora', 'Zora', 'evm', true, false, 7777777, 'https://explorer.zora.energy/tx/{tx}', 'https://explorer.zora.energy/token/{address}', 45),
  ('mode', 'Mode', 'evm', true, false, 34443, 'https://explorer.mode.network/tx/{tx}', 'https://explorer.mode.network/token/{address}', 46),
  ('manta', 'Manta', 'evm', true, false, 169, 'https://pacific-explorer.manta.network/tx/{tx}', 'https://pacific-explorer.manta.network/token/{address}', 47),
  ('taiko', 'Taiko', 'evm', true, false, 167000, 'https://taikoscan.io/tx/{tx}', 'https://taikoscan.io/token/{address}', 48),
  ('ink', 'Ink', 'evm', true, false, 57073, 'https://explorer.inkonchain.com/tx/{tx}', 'https://explorer.inkonchain.com/token/{address}', 49),
  ('soneium', 'Soneium', 'evm', true, false, 1868, 'https://soneium.blockscout.com/tx/{tx}', 'https://soneium.blockscout.com/token/{address}', 50),
  ('worldchain', 'World Chain', 'evm', true, false, 480, 'https://worldscan.org/tx/{tx}', 'https://worldscan.org/token/{address}', 51),
  ('gnosischain', 'Gnosis', 'evm', true, false, 100, 'https://gnosisscan.io/tx/{tx}', 'https://gnosisscan.io/token/{address}', 52),
  ('kaia', 'Kaia', 'evm', true, false, 8217, 'https://kaiascan.io/tx/{tx}', 'https://kaiascan.io/token/{address}', 53),
  ('flare', 'Flare', 'evm', true, false, 14, 'https://flare-explorer.flare.network/tx/{tx}', 'https://flare-explorer.flare.network/token/{address}', 54),
  ('bob', 'BOB', 'evm', true, false, 60808, 'https://explorer.gobob.xyz/tx/{tx}', 'https://explorer.gobob.xyz/token/{address}', 55),
  ('katana', 'Katana', 'evm', true, false, 747474, 'https://katanascan.com/tx/{tx}', 'https://katanascan.com/token/{address}', 56),
  ('plasma', 'Plasma', 'evm', true, false, 9745, 'https://plasmascan.to/tx/{tx}', 'https://plasmascan.to/token/{address}', 57),
  ('megaeth', 'MegaETH', 'evm', true, false, 4326, 'https://megaexplorer.xyz/tx/{tx}', 'https://megaexplorer.xyz/token/{address}', 58),
  ('osmosis', 'Osmosis', 'other', true, false, null, 'https://www.mintscan.io/osmosis/tx/{tx}', null, 59),
  ('injective', 'Injective', 'other', true, false, null, 'https://explorer.injective.network/transaction/{tx}', null, 60),
  ('starknet', 'Starknet', 'other', true, false, null, 'https://voyager.online/tx/{tx}', 'https://voyager.online/token/{address}', 61),
  ('algorand', 'Algorand', 'other', true, false, null, 'https://allo.info/tx/{tx}', 'https://allo.info/asset/{address}', 62),
  ('cardano', 'Cardano', 'other', true, false, null, 'https://cardanoscan.io/transaction/{tx}', 'https://cardanoscan.io/token/{address}', 63),
  ('hedera', 'Hedera', 'other', true, false, null, 'https://hashscan.io/mainnet/transaction/{tx}', 'https://hashscan.io/mainnet/token/{address}', 64),
  ('multiversx', 'MultiversX', 'other', true, false, null, 'https://explorer.multiversx.com/transactions/{tx}', 'https://explorer.multiversx.com/tokens/{address}', 65)
on conflict (id) do nothing;
