/**
 * Chain logos served from /public/chains (downloaded once; no hotlinking). Sources: trustwallet/assets (MIT) as PNG resized to 96 px,
 * 0xa3k5/web3icons (MIT) as SVG where Trust Wallet has none. Chains without a logo get a lettered badge.
 */
export const CHAIN_LOGOS: Record<string, string> = {
  "abstract": "/chains/abstract.svg",
  "algorand": "/chains/algorand.png",
  "apechain": "/chains/apechain.svg",
  "aptos": "/chains/aptos.png",
  "arbitrum": "/chains/arbitrum.png",
  "arc": "/chains/arc.png",
  "avalanche": "/chains/avalanche.png",
  "base": "/chains/base.png",
  "berachain": "/chains/berachain.svg",
  "blast": "/chains/blast.png",
  "bob": "/chains/bob.svg",
  "bsc": "/chains/bsc.png",
  "cardano": "/chains/cardano.png",
  "celo": "/chains/celo.png",
  "cronos": "/chains/cronos.png",
  "ethereum": "/chains/ethereum.png",
  "fantom": "/chains/fantom.png",
  "flare": "/chains/flare.svg",
  "gnosischain": "/chains/gnosischain.png",
  "hedera": "/chains/hedera.png",
  "hyperevm": "/chains/hyperevm.png",
  "injective": "/chains/injective.png",
  "ink": "/chains/ink.svg",
  "kaia": "/chains/kaia.png",
  "katana": "/chains/katana.svg",
  "linea": "/chains/linea.png",
  "manta": "/chains/manta.png",
  "mantle": "/chains/mantle.png",
  "megaeth": "/chains/megaeth.png",
  "metis": "/chains/metis.png",
  "mode": "/chains/mode.svg",
  "monad": "/chains/monad.png",
  "moonbeam": "/chains/moonbeam.png",
  "multiversx": "/chains/multiversx.png",
  "near": "/chains/near.png",
  "optimism": "/chains/optimism.png",
  "osmosis": "/chains/osmosis.png",
  "plasma": "/chains/plasma.png",
  "polygon": "/chains/polygon.png",
  "pulsechain": "/chains/pulsechain.svg",
  "robinhood": "/chains/robinhood.svg",
  "scroll": "/chains/scroll.png",
  "seiv2": "/chains/seiv2.png",
  "solana": "/chains/solana.png",
  "soneium": "/chains/soneium.svg",
  "sonic": "/chains/sonic.png",
  "starknet": "/chains/starknet.svg",
  "sui": "/chains/sui.png",
  "taiko": "/chains/taiko.svg",
  "ton": "/chains/ton.png",
  "tron": "/chains/tron.png",
  "unichain": "/chains/unichain.svg",
  "worldchain": "/chains/worldchain.svg",
  "xlayer": "/chains/xlayer.png",
  "zksync": "/chains/zksync.png",
  "zora": "/chains/zora.svg"
};
